### ISSUE TITLE
Consolidation of python API wrapper effort

### ISSUE THREAD

**Issue by wanderanimrod** [rapidpro/rapidpro-python#1]
Hi Rowan,

 I would like to contribute a python API wrapper for RapidPro similar to the one you have here. 

My idea though is to create one in form of a django app (with already made models and services) that can easily be plugged into a django app. The purpose is to reduce the models and services boilerplate developers have to write when they are integrating their apps with RapidPro. 

My impression is that you are taking the direction of making this one a plain python wrapper, which makes it great for compatibility with other python environments (like plain python apps and frameworks like flask), making it different from the django-targeted wrapper I intend to create. 

I would like to know if the assumption I am making about your direction is correct, and if you think we can collaborate on some common aspects if there are any ( I can certainly see the possibility of the django app using your wrapper).

Thanks.

**Comment by nicpottier** [comment]
Hi there,

This library is meant to be a library only. We do have some other projects that try to do more, such as /rapidpro/dash but this library will remain something minimal.

Cheers,

-Nic

**Comment by wanderanimrod** [comment]
Thanks

**Comment by rowanseymour** [comment]
Sorry missed this until now. Your assumption is correct - this only ever going to be a simple wrapper for the API. Something you might want to utilize for a more complex app based project such as what you're describing.
