### ISSUE TITLE
get_flows missing in V2

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro-python#20]
I have noticed that `get_flows()` is missing on V2 client. I have also noticed that Rapidpro is not exposing `/api/v2/flows` is there a specific reason for getting rid of this endpoint? Or is there another place to get the flow detail with the API?

**Comment by rowanseymour** [comment]
There's a lot is missing on v2 at the minute - it's still under development. But we definitely intend to include this endpoint in v2 and almost of all of the other endpoints from v1. I'm actually going to working on that in the next month, so hopefully we can get v2 ready soon.
