### ISSUE TITLE
TembaBadRequestError exception with create_contact

### ISSUE THREAD

**Issue by gravitz** [rapidpro/rapidpro-python#62]
Hi Team,

For the past few days we have observed scripts we wrote and have used before, that use create_contact endpoint are now throwing a TembaBadRequestError exception and no further information. 

![image](https://user-images.githubusercontent.com/10649892/55093515-929c3180-50c5-11e9-9cf5-ac440916968d.png)

Getter api functions appear to be working as expected.

Other than the homepage (https://rapidpro-python.readthedocs.io/en/latest/index.html), the api documentation pages appear to no longer have content.

Please advise.

Engel

**Comment by rowanseymour** [comment]
Hi @gravitz can you try making that request directly to the API (can use the API explorer page) and see what the response is? Need to know if there is any error message coming back from RapidPro at all.

**Comment by norkans7** [comment]
@gravitz I think you are missing a + in the URN

**Comment by norkans7** [comment]
@gravitz I double checked and saw the + is not required, however the phone number in the URN must be valid

**Comment by norkans7** [comment]
You want to use a try/except to have more info on the exception raised

**Comment by gravitz** [comment]
Ni Norbert. What I shared is an excerpt from code that has behaved correctly in the past (the URN is made up but this is not the issue).

**Comment by norkans7** [comment]
Are you sure you have the latest version?
Try to use a try/except and get more info on the exception raised.

**Comment by gravitz** [comment]
Hi @norkans7 

I was running v 2.4 and updated to 2.5.1 and tried it with a urn (with a + sign) which seemed to fix it.
