### ISSUE TITLE
Loosen pytz dependencies

### ISSUE THREAD

**Issue by chris-erickson** [rapidpro/rapidpro-python#75]
Could we expand the pytz dependency?  Wondering if this is just a consequence of a quasi-semver problem with the year rolling over.

```
ERROR: Cannot install -r requirements.txt (line 16) and pytz==2021.1 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested pytz==2021.1
    rapidpro-python 2.8.1 depends on pytz<2021.0 and >=2020.4
```

**Comment by rowanseymour** [comment]
This must be an old version of the code because `requirements.txt` is gone and it's all poetry now. Recently releases of pip got stricter about conflicts which was part of the motivation of moving to poetry to make it easier to keep dependencies up to date.

**Comment by tybritten** [comment]
@rowanseymour This still applies with poetry. `"^2020.4"` only allows` 2020.x` above 4. If you changed the pyproject.toml to `">=2020.4"` it would allow ptz versions of 2021.x as well.

**Comment by rowanseymour** [comment]
Are you seeing dependency conflicts installing from poetry? If we just want to make sure `poetry update` always gets the latest pytz, we can change the version to `*`.

**Comment by tybritten** [comment]
yeah that works. the issue we hit is we have the newest pytz and rapidpro-python in a project and that's causing the conflict

**Comment by rowanseymour** [comment]
Ah ok this is installing into another project - made new release at https://pypi.org/project/rapidpro-python/2.8.2/
