### ISSUE TITLE
temba_client.exceptions.TembaBadRequestError: Must be a string or integer

### ISSUE THREAD

**Issue by Georgeygigz** [rapidpro/rapidpro-python#76]
Hi all am facing this error on` bulk_add_contacts`  method. 
`temba_client.exceptions.TembaBadRequestError: Must be a string or integer`

This is how my implementation looks like

```
contacts = [{"URN:Tel":"072400000", "Name":""}]
temba_instance.bulk_add_contacts(contacts, 'Test')
```
What could I be doing wrong?Kindly help

**Comment by rowanseymour** [comment]
The client methods are designed to work with either the objects returned by other client methods, or the raw identifiers (UUIDs etc). For `bulk_add_contacts` the first param needs to be a list of contact objects or URNs or UUIDs, and the second param a group object or group UUID or group name, e.g.

```python
contacts = ["tel:072400000"]
temba_instance.bulk_add_contacts(contacts, "Test")
```
